### ISSUE TITLE
FR: Youtube Chat

### ISSUE THREAD

**Issue by JayGreentree** [aodihis/craftcms-video-utils#9]
It would awesome to have an option for embedding YouTube's chat if video is an active livestream

Example:

https://www.youtube.com/live_chat?v=$SomeVideoID&amp;embed_domain=DomainName.com

**Comment by aodihis** [comment]
Hi, @JayGreentree, sorry I got occupied in the past month.  I have made an update related to this feature, please refer to version 3.0.1.
Thank you.

**Comment by JayGreentree** [comment]
Sorry I haven't responded sooner. Thanks for your efforts in this but there is one minor issue. the code adds the http(s):// but only needs to show domain.com etc

**Comment by aodihis** [comment]
@JayGreentree, I see thanks for the feedback. I will update it this week.

**Comment by aodihis** [comment]
@JayGreentree please refer to version 3.0.2 to show only domain without scheme.

**Comment by jaysavage83** [comment]
Thanks it works perfectly now.
